### PR TITLE
webui

### PR DESCRIPTION
**Pull request by Casprine**
@jajoosam and @leovarmak 
I just completed the webui frontend for the project
maybe you guys can work the api calls and the backend stuffs
not really good with.
lemme know if you need any changes

### CODE REVIEW

**Comment by jajoosam** [comment]
@Casprine Is this the web UI or the website for libert?
@leovarmak You should make a JSON API for libert, and @Casprine can use that API for the web UI, yes?

**Comment by Casprine** [comment]
@jajoosam it's the website not the web UI. Will work on the UI with @leovarmak 
@leovarmak try and contact me asap

**Comment by leovarmak** [comment]
@Casprine Sure thing man.

**Comment by leovarmak** [comment]
Close the pull request now ?

**Pull request closed without merging**
